sonar.projectKey=mawa9it-jesserbensalah-2025
sonar.organization=mawa9it-jesserbensalah-2025
sonar.projectName=MAWA9IT 
sonar.sources=backend/src/caspanne
sonar.tests=backend/src/caspanne
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.typescript.lcov.reportPaths=backend/coverage-caspanne/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.host.url=https://sonarcloud.io